version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      time: "04:00"
    assignees:
      - tobealive
    commit-message:
      prefix: ":arrow_up: "

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "04:00"
    assignees:
      - tobealive
    commit-message:
      prefix: ":arrow_up: "
